version: '3.4'

services:
  catalogdb:
    image: mongo
    container_name: catalog-mongo-db
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=appuser
      - MONGO_INITDB_ROOT_PASSWORD=Password1
    ports: 
      - 27017:27017
    volumes:
      - catalog-mongo-data:/data/db

  basketdb:
    image: redis
    container_name: basket-redis-db
    restart: on-failure
    ports: 
      - 6379:6379    
    volumes:
      - basket-data:/data

  discountdb:
    image: postgres
    container_name: discount-postgres-db
    restart: on-failure
    environment: 
      - POSTGRES_USER=appuser
      - POSTGRES_PASSWORD=P@ssword1
    ports: 
      - 5432:5432    
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=geraldmaale@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=P@ssword1
    ports:
      - 5050:80
    volumes:
      - pgadmin_data:/root/.pgadmin

  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    restart: always
    ports:
      - 8080:8000
      - 9443:9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  catalog.api:
    container_name: catalog-api
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile    
    environment:
      - DatabaseSettings:Credentials=mongodb://appuser:Password1@catalogdb:27017
      - DatabaseSettings:DatabaseName=CatalogDb
    ports:
      - "8000:80"

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    container_name: basket-api
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile
    environment:
      - Redis:ConnectionString=basketdb:6379
      - GrpcSettings:DiscountUrl=discount.api:8002
    depends_on:
     - basketdb
    ports:
      - "8001:80"

  discount.api:
    image: ${DOCKER_REGISTRY-}discountapi
    container_name: discount-api
    build:
      context: .
      dockerfile: Services/Discount/Discount.API/Dockerfile
    environment:
      - "DatabaseSettings:ConnectionString=Server=discountdb;Port=5432;Database=DiscountDb;User Id=appuser;Password=P@ssword1;"
    depends_on:
     - discountdb
    ports:
      - "8002:80"

volumes:
  catalog-mongo-data:   
  basket-data:
  portainer_data:
  pgdata:
  pgadmin_data: