version: '3.4'

services:
  catalogdb:
    image: mongo
    restart: always        
    volumes:
      - catalog-mongo-data:/data/db

  catalog.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80     
    depends_on:
      - catalogdb
    ports:
      - "8000:80"
      - "9000:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
