version: '3.4'

services:

  mongoserver:
    image: mongo    

  rediserver:
    image: redis
    

  postgreserver:
    image: postgres


  pgadmin:
    image: dpage/pgadmin4

    
  portainer:
    image: portainer/portainer-ce

    
  rabbitmq:
    image: rabbitmq:3.9-management

    
  elastic01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.1

    
  kibana:
    image: docker.elastic.co/kibana/kibana:7.16.1

    
  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile

      
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile


  discount.grpc:
    image: ${DOCKER_REGISTRY-}discountgrpc
    build:
      context: .
      dockerfile: Services/Discount/Discount.Grpc/Dockerfile


  ordering.api:
    image: ${DOCKER_REGISTRY-}orderingapi
    build:
      context: .
      dockerfile: Services/Ordering/Ordering.API/Dockerfile

