version: '3.4'

services:
  catalogdb:
    image: mongo
    container_name: catalog-mongo-server
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=appuser
      - MONGO_INITDB_ROOT_PASSWORD=Password1
    ports: 
      - 27017:27017
    volumes:
      - catalog-mongo-data:/data/db

  redis:
    image: redis
    container_name: redis-api
    restart: on-failure
    ports: 
      - 6379:6379    
    volumes:
      - redis-data:/data

  catalog.api:
    container_name: "catalog-api"
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile    
    environment:
      - DatabaseSettings:Credentials=mongodb://appuser:Password1@catalogdb:27017
      - DatabaseSettings:DatabaseName=ProductsDb
  


volumes:
  catalog-mongo-data:   
  redis-data: